name: Deploy BruceBrow

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz projekt
        uses: actions/checkout@v4

      - name: Przygotuj stronę
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src

      - name: Opublikuj BruceBrow
        uses: actions/deploy-pages@v4
